server:
  port: 9600

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/blogtube?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  redis:
    host: localhost
    port: 6379

jwt:
  secret: tomoyaHasASecretKey
  expiration: 604800 # = 7*24*60*60
  tokenHeader: Authorization
  tokenHead: Bearer
  claim:
    username: sub
    created: iat

mybatis:
  config-location: classpath:config/mybatis-config.xml
  mapper-locations:
  - classpath:mapper/*.xml