server:
  port: 9600

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/wechat?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  redis:
    host: localhost
    port: 6379
    database: 0
    password: 

  mail:
    host: smtp.163.com
    username: peng-jiahui@163.com
    password: peng-476612

redis:
  key:
    prefix:
      liveCode: "URRIGHT:livecode:"
    expire:
      liveCode: 120

mail:
  liveCode:
    subject: "URRIGHT验证码"
    content: 
      prefix: "您的验证码为："
      suffix: "。2分钟内有效。"
    

jwt:
  secret: tomoyaHasASecretKey
  expiration: 604800 # = 7*24*60*60
  tokenHeader: Authorization
  tokenHead: Bearer
  claim:
    username: sub
    created: iat

mybatis:
  config-location: classpath:config/mybatis-config.xml
  mapper-locations:
  - classpath:mapper/*.xml